id: P55D225C2
initial_creation_type: ocr
source_metadata:
  volumes:
    4cbb5805c9714e59a58fc2be77eb3d4a:
      base_file: v055.txt
      image_group_id: I1PD95900
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་འབུམ་པ་དང་། ཉི་ཁྲི་ལྔ་སྟོང་པ་དང་། ཁྲི་བརྒྱད་སྟོང་པའི་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1470
      volume_number: 55
